# Stage 1: Build binary
FROM golang:1.25.6-alpine AS builder

# Cài thêm git nếu cần go mod có package từ github
RUN apk add --no-cache git

WORKDIR /app

# Copy go mod files and download dependencies first (layer caching)
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

RUN go mod vendor
# Đặt lại thư mục làm việc để build chính xác
WORKDIR /app/cmd/worker

# Build the Go binary
RUN go build -mod=vendor -o worker .

# Stage 2: Minimal image
FROM alpine:latest

WORKDIR /app/cmd/worker

# Copy binary từ builder stage
COPY --from=builder /app/cmd/worker/worker .

# Copy .env nếu cần khi runtime
COPY --from=builder /app/.env /app/.env

# Run the binary
CMD ["./worker"]