services:
  api:
    build:
      dockerfile: Dockerfile.staging
    container_name: api_app_ets_staging
    env_file: .env
    expose:
      - "8082"
    environment:
      - VIRTUAL_HOST=staging-api.toeicviet.com
      - LETSENCRYPT_HOST=staging-api.toeicviet.com
      - LETSENCRYPT_EMAIL=ml2673572@gmail.com
      - VIRTUAL_PORT=8082
    networks:
      - app-network
    restart: unless-stopped
  # worker:
  #   build:
  #     dockerfile: Dockerfile.worker
  #   container_name: worker_app_ets_staging
  #   env_file: .env
  #   networks:
  #     - app-network
  #   restart: unless-stopped
networks:
  app-network:
    external: true
    name: app-network